### PR TITLE
Fix check for OS platform

### PR DESCRIPTION
**Pull request by ray-milkey**

### CODE REVIEW

**Review by eroshiva — APPROVED** [review]

**Comment by eroshiva** [comment]
retest this please

**Comment by eroshiva** [comment]
retest this please

**Comment by eroshiva** [comment]
retest this please

**Comment by eroshiva** [comment]
retest this please

**Comment by eroshiva** [comment]
retest this please

**Comment by ray-milkey** [comment]
retest this please

**Pull request merged**
